# Generated by Django 3.2.4 on 2021-06-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='user',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Reward')], default=1),
            preserve_default=False,
        ),
    ]
