# Generated by Django 3.2.4 on 2021-06-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_tax_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='tax',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Wednesday'),
        ),
    ]
